using MediatR;
using Microsoft.EntityFrameworkCore;
using MajlesMefa.Back.Dtos;
using MajlesMefa.Back.Entities;
using MajlesMefa.Back.Enums;
using MajlesMefa.Back.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MajlesMefa.Back.UseCases.Commmands.SeedCitiesCommand
{
    public class SeedCitiesCommandHandler : IRequestHandler<SeedCitiesCommand>
    {
        private readonly IUnitOfWork _unitOfWork;

        public SeedCitiesCommandHandler(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task Handle(SeedCitiesCommand request, CancellationToken cancellationToken)
        {
            var list = GetCities();
            var grouped = list.GroupBy(x => x.ParentCityName);
            var id = await _unitOfWork.UserRepository
                .NoTracking
                .Where(x => x.UserRoles.Any(r => r.Role.RoleType == RoleTypeEnum.Admin))
                .Select(x => x.UserId)
                .FirstOrDefaultAsync();
            foreach (var item in grouped)
            {
                var parentCity = new CityEntity()
                {
                    Name = item.Key,
                    CreatorUserId = id
                };
                _unitOfWork.CityRepository.Add(parentCity);
                foreach (var subItem in item)
                {
                    var city = new CityEntity()
                    {
                        Name = subItem.CityName,
                        Parent = parentCity,
                        CreatorUserId = id
                    };
                    _unitOfWork.CityRepository.Add(city);
                }
            }
            await _unitOfWork.SaveChangesAsync(cancellationToken);
        }


        #region helper
        private List<CitySeedDto> GetCities()
        {
            var list = new List<CitySeedDto>
            {
                new CitySeedDto("اردبيل","اردبيل"),
                new CitySeedDto("اردبيل","اصلاندوز"),
                new CitySeedDto("اردبيل","آبي بيگلو"),
                new CitySeedDto("اردبيل","بيله سوار"),
                new CitySeedDto("اردبيل","پارس آباد"),
                new CitySeedDto("اردبيل","تازه كند"),
                new CitySeedDto("اردبيل","تازه كندانگوت"),
                new CitySeedDto("اردبيل","جعفرآباد"),
                new CitySeedDto("اردبيل","خلخال"),
                new CitySeedDto("اردبيل","رضي"),
                new CitySeedDto("اردبيل","سرعين"),
                new CitySeedDto("اردبيل","عنبران"),
                new CitySeedDto("اردبيل","فخرآباد"),
                new CitySeedDto("اردبيل","كلور"),
                new CitySeedDto("اردبيل","كوراييم"),
                new CitySeedDto("اردبيل","گرمي"),
                new CitySeedDto("اردبيل","گيوي"),
                new CitySeedDto("اردبيل","لاهرود"),
                new CitySeedDto("اردبيل","مرادلو"),
                new CitySeedDto("اردبيل","مشگين شهر"),
                new CitySeedDto("اردبيل","نمين"),
                new CitySeedDto("اردبيل","نير"),
                new CitySeedDto("اردبيل","هشتجين"),
                new CitySeedDto("اردبيل","هير"),
                new CitySeedDto("اصفهان","ابريشم"),
                new CitySeedDto("اصفهان","ابوزيدآباد"),
                new CitySeedDto("اصفهان","اردستان"),
                new CitySeedDto("اصفهان","اژيه"),
                new CitySeedDto("اصفهان","اصفهان"),
                new CitySeedDto("اصفهان","افوس"),
                new CitySeedDto("اصفهان","انارك"),
                new CitySeedDto("اصفهان","ايمانشهر"),
                new CitySeedDto("اصفهان","آران وبيدگل"),
                new CitySeedDto("اصفهان","بادرود"),
                new CitySeedDto("اصفهان","باغ بهادران"),
                new CitySeedDto("اصفهان","بافران"),
                new CitySeedDto("اصفهان","برزك"),
                new CitySeedDto("اصفهان","برف انبار"),
                new CitySeedDto("اصفهان","بوئين ومياندشت"),
                new CitySeedDto("اصفهان","بهاران شهر"),
                new CitySeedDto("اصفهان","بهارستان"),
                new CitySeedDto("اصفهان","پيربكران"),
                new CitySeedDto("اصفهان","تودشك"),
                new CitySeedDto("اصفهان","تيران"),
                new CitySeedDto("اصفهان","جندق"),
                new CitySeedDto("اصفهان","جوزدان"),
                new CitySeedDto("اصفهان","جوشقان وكامو"),
                new CitySeedDto("اصفهان","چادگان"),
                new CitySeedDto("اصفهان","چرمهين"),
                new CitySeedDto("اصفهان","چمگردان"),
                new CitySeedDto("اصفهان","حبيب آباد"),
                new CitySeedDto("اصفهان","حسن آباد"),
                new CitySeedDto("اصفهان","حنا"),
                new CitySeedDto("اصفهان","خالدآباد"),
                new CitySeedDto("اصفهان","خميني شهر"),
                new CitySeedDto("اصفهان","خوانسار"),
                new CitySeedDto("اصفهان","خور"),
                new CitySeedDto("اصفهان","خوراسگان"),
                new CitySeedDto("اصفهان","خورزوق"),
                new CitySeedDto("اصفهان","داران"),
                new CitySeedDto("اصفهان","دامنه"),
                new CitySeedDto("اصفهان","درچه پياز"),
                new CitySeedDto("اصفهان","دستگرد"),
                new CitySeedDto("اصفهان","دولت آباد"),
                new CitySeedDto("اصفهان","دهاقان"),
                new CitySeedDto("اصفهان","دهق"),
                new CitySeedDto("اصفهان","ديزيچه"),
                new CitySeedDto("اصفهان","رزوه"),
                new CitySeedDto("اصفهان","رضوانشهر"),
                new CitySeedDto("اصفهان","زاينده رود"),
                new CitySeedDto("اصفهان","زرين شهر"),
                new CitySeedDto("اصفهان","زواره"),
                new CitySeedDto("اصفهان","زيباشهر"),
                new CitySeedDto("اصفهان","سده لنجان"),
                new CitySeedDto("اصفهان","سفيدشهر"),
                new CitySeedDto("اصفهان","سگزي"),
                new CitySeedDto("اصفهان","سميرم"),
                new CitySeedDto("اصفهان","شاپورآباد"),
                new CitySeedDto("اصفهان","شاهين شهر"),
                new CitySeedDto("اصفهان","شهرضا"),
                new CitySeedDto("اصفهان","طالخونچه"),
                new CitySeedDto("اصفهان","عسگران"),
                new CitySeedDto("اصفهان","علويچه"),
                new CitySeedDto("اصفهان","فرخي"),
                new CitySeedDto("اصفهان","فريدونشهر"),
                new CitySeedDto("اصفهان","فلاورجان"),
                new CitySeedDto("اصفهان","فولادشهر"),
                new CitySeedDto("اصفهان","قمصر"),
                new CitySeedDto("اصفهان","قهجاورستان"),
                new CitySeedDto("اصفهان","قهدريجان"),
                new CitySeedDto("اصفهان","كاشان"),
                new CitySeedDto("اصفهان","كركوند"),
                new CitySeedDto("اصفهان","كليشادوسودرجان"),
                new CitySeedDto("اصفهان","كمشچه"),
                new CitySeedDto("اصفهان","كمه"),
                new CitySeedDto("اصفهان","كوشك"),
                new CitySeedDto("اصفهان","كوهپايه"),
                new CitySeedDto("اصفهان","كهريزسنگ"),
                new CitySeedDto("اصفهان","گرگاب"),
                new CitySeedDto("اصفهان","گزبرخوار"),
                new CitySeedDto("اصفهان","گلپايگان"),
                new CitySeedDto("اصفهان","گلدشت"),
                new CitySeedDto("اصفهان","گلشن"),
                new CitySeedDto("اصفهان","گلشهر"),
                new CitySeedDto("اصفهان","گوگد"),
                new CitySeedDto("اصفهان","لاي بيد"),
                new CitySeedDto("اصفهان","مباركه"),
                new CitySeedDto("اصفهان","محمدآباد"),
                new CitySeedDto("اصفهان","مشكات"),
                new CitySeedDto("اصفهان","منظريه"),
                new CitySeedDto("اصفهان","مهاباد"),
                new CitySeedDto("اصفهان","ميمه"),
                new CitySeedDto("اصفهان","نائين"),
                new CitySeedDto("اصفهان","نجف آباد"),
                new CitySeedDto("اصفهان","نصرآباد"),
                new CitySeedDto("اصفهان","نطنز"),
                new CitySeedDto("اصفهان","نوش آباد"),
                new CitySeedDto("اصفهان","نياسر"),
                new CitySeedDto("اصفهان","نيك آباد"),
                new CitySeedDto("اصفهان","ورزنه"),
                new CitySeedDto("اصفهان","ورنامخواست"),
                new CitySeedDto("اصفهان","وزوان"),
                new CitySeedDto("اصفهان","ونك"),
                new CitySeedDto("اصفهان","هرند"),
                new CitySeedDto("البرز","اشتهارد"),
                new CitySeedDto("البرز","آسارا"),
                new CitySeedDto("البرز","تنكمان"),
                new CitySeedDto("البرز","چهارباغ"),
                new CitySeedDto("البرز","سيف آباد"),
                new CitySeedDto("البرز","شهرجديدهشتگرد"),
                new CitySeedDto("البرز","طالقان"),
                new CitySeedDto("البرز","كرج"),
                new CitySeedDto("البرز","كمال شهر"),
                new CitySeedDto("البرز","كوهسار"),
                new CitySeedDto("البرز","گرمدره"),
                new CitySeedDto("البرز","ماهدشت"),
                new CitySeedDto("البرز","محمدشهر"),
                new CitySeedDto("البرز","مشكين دشت"),
                new CitySeedDto("البرز","نظرآباد"),
                new CitySeedDto("البرز","هشتگرد"),
                new CitySeedDto("ايلام","اركواز"),
                new CitySeedDto("ايلام","ايلام"),
                new CitySeedDto("ايلام","ايوان"),
                new CitySeedDto("ايلام","آبدانان"),
                new CitySeedDto("ايلام","آسمان آباد"),
                new CitySeedDto("ايلام","بدره"),
                new CitySeedDto("ايلام","پهله"),
                new CitySeedDto("ايلام","توحيد"),
                new CitySeedDto("ايلام","چوار"),
                new CitySeedDto("ايلام","دره شهر"),
                new CitySeedDto("ايلام","دلگشا"),
                new CitySeedDto("ايلام","دهلران"),
                new CitySeedDto("ايلام","زرنه"),
                new CitySeedDto("ايلام","سراب باغ"),
                new CitySeedDto("ايلام","سرابله"),
                new CitySeedDto("ايلام","صالح آباد"),
                new CitySeedDto("ايلام","لومار"),
                new CitySeedDto("ايلام","مورموري"),
                new CitySeedDto("ايلام","موسيان"),
                new CitySeedDto("ايلام","مهران"),
                new CitySeedDto("ايلام","ميمه "),
                new CitySeedDto("آذربايجان شرقي","اسكو"),
                new CitySeedDto("آذربايجان شرقي","اهر"),
                new CitySeedDto("آذربايجان شرقي","ايلخچي"),
                new CitySeedDto("آذربايجان شرقي","آبش احمد"),
                new CitySeedDto("آذربايجان شرقي","آذرشهر"),
                new CitySeedDto("آذربايجان شرقي","آقكند"),
                new CitySeedDto("آذربايجان شرقي","باسمنج"),
                new CitySeedDto("آذربايجان شرقي","بخشايش"),
                new CitySeedDto("آذربايجان شرقي","بستان آباد"),
                new CitySeedDto("آذربايجان شرقي","بناب"),
                new CitySeedDto("آذربايجان شرقي","بناب جديد"),
                new CitySeedDto("آذربايجان شرقي","تبريز"),
                new CitySeedDto("آذربايجان شرقي","ترك"),
                new CitySeedDto("آذربايجان شرقي","تركمانچاي"),
                new CitySeedDto("آذربايجان شرقي","تسوج"),
                new CitySeedDto("آذربايجان شرقي","تيكمه داش"),
                new CitySeedDto("آذربايجان شرقي","جلفا"),
                new CitySeedDto("آذربايجان شرقي","خاروانا"),
                new CitySeedDto("آذربايجان شرقي","خامنه"),
                new CitySeedDto("آذربايجان شرقي","خراجو"),
                new CitySeedDto("آذربايجان شرقي","خسروشهر"),
                new CitySeedDto("آذربايجان شرقي","خمارلو"),
                new CitySeedDto("آذربايجان شرقي","خواجه"),
                new CitySeedDto("آذربايجان شرقي","دوزدوزان"),
                new CitySeedDto("آذربايجان شرقي","زرنق"),
                new CitySeedDto("آذربايجان شرقي","زنوز"),
                new CitySeedDto("آذربايجان شرقي","سراب"),
                new CitySeedDto("آذربايجان شرقي","سردرود"),
                new CitySeedDto("آذربايجان شرقي","سيس"),
                new CitySeedDto("آذربايجان شرقي","سيه رود"),
                new CitySeedDto("آذربايجان شرقي","شبستر"),
                new CitySeedDto("آذربايجان شرقي","شربيان"),
                new CitySeedDto("آذربايجان شرقي","شرفخانه"),
                new CitySeedDto("آذربايجان شرقي","شندآباد"),
                new CitySeedDto("آذربايجان شرقي","شهرجديدسهند"),
                new CitySeedDto("آذربايجان شرقي","صوفيان"),
                new CitySeedDto("آذربايجان شرقي","عجب شير"),
                new CitySeedDto("آذربايجان شرقي","قره آغاج"),
                new CitySeedDto("آذربايجان شرقي","كشكسراي"),
                new CitySeedDto("آذربايجان شرقي","كلوانق"),
                new CitySeedDto("آذربايجان شرقي","كليبر"),
                new CitySeedDto("آذربايجان شرقي","كوزه كنان"),
                new CitySeedDto("آذربايجان شرقي","گوگان"),
                new CitySeedDto("آذربايجان شرقي","ليلان"),
                new CitySeedDto("آذربايجان شرقي","مراغه"),
                new CitySeedDto("آذربايجان شرقي","مرند"),
                new CitySeedDto("آذربايجان شرقي","ملكان"),
                new CitySeedDto("آذربايجان شرقي","ممقان"),
                new CitySeedDto("آذربايجان شرقي","مهربان"),
                new CitySeedDto("آذربايجان شرقي","ميانه"),
                new CitySeedDto("آذربايجان شرقي","نظركهريزي"),
                new CitySeedDto("آذربايجان شرقي","وايقان"),
                new CitySeedDto("آذربايجان شرقي","ورزقان"),
                new CitySeedDto("آذربايجان شرقي","هاديشهر"),
                new CitySeedDto("آذربايجان شرقي","هريس"),
                new CitySeedDto("آذربايجان شرقي","هشترود"),
                new CitySeedDto("آذربايجان شرقي","هوراند"),
                new CitySeedDto("آذربايجان شرقي","يامچي"),
                new CitySeedDto("آذربايجان غربي","اروميه"),
                new CitySeedDto("آذربايجان غربي","اشنويه"),
                new CitySeedDto("آذربايجان غربي","ايواوغلي"),
                new CitySeedDto("آذربايجان غربي","آواجيق"),
                new CitySeedDto("آذربايجان غربي","باروق"),
                new CitySeedDto("آذربايجان غربي","بازرگان"),
                new CitySeedDto("آذربايجان غربي","بوكان"),
                new CitySeedDto("آذربايجان غربي","پلدشت"),
                new CitySeedDto("آذربايجان غربي","پيرانشهر"),
                new CitySeedDto("آذربايجان غربي","تازه شهر"),
                new CitySeedDto("آذربايجان غربي","تكاب"),
                new CitySeedDto("آذربايجان غربي","چهاربرج"),
                new CitySeedDto("آذربايجان غربي","خليفان"),
                new CitySeedDto("آذربايجان غربي","خوي"),
                new CitySeedDto("آذربايجان غربي","ديزج ديز"),
                new CitySeedDto("آذربايجان غربي","ربط"),
                new CitySeedDto("آذربايجان غربي","سردشت"),
                new CitySeedDto("آذربايجان غربي","سرو"),
                new CitySeedDto("آذربايجان غربي","سلماس"),
                new CitySeedDto("آذربايجان غربي","سيلوانه"),
                new CitySeedDto("آذربايجان غربي","سيمينه"),
                new CitySeedDto("آذربايجان غربي","سيه چشمه"),
                new CitySeedDto("آذربايجان غربي","شاهين دژ"),
                new CitySeedDto("آذربايجان غربي","شوط"),
                new CitySeedDto("آذربايجان غربي","فيرورق"),
                new CitySeedDto("آذربايجان غربي","قره ضياءالدين"),
                new CitySeedDto("آذربايجان غربي","قطور"),
                new CitySeedDto("آذربايجان غربي","قوشچي"),
                new CitySeedDto("آذربايجان غربي","كشاورز"),
                new CitySeedDto("آذربايجان غربي","گردكشانه"),
                new CitySeedDto("آذربايجان غربي","ماكو"),
                new CitySeedDto("آذربايجان غربي","محمديار"),
                new CitySeedDto("آذربايجان غربي","محمودآباد"),
                new CitySeedDto("آذربايجان غربي","مهاباد "),
                new CitySeedDto("آذربايجان غربي","مياندوآب"),
                new CitySeedDto("آذربايجان غربي","ميرآباد"),
                new CitySeedDto("آذربايجان غربي","نالوس"),
                new CitySeedDto("آذربايجان غربي","نقده"),
                new CitySeedDto("آذربايجان غربي","نوشين"),
                new CitySeedDto("بوشهر","امام حسن"),
                new CitySeedDto("بوشهر","انارستان"),
                new CitySeedDto("بوشهر","اهرم"),
                new CitySeedDto("بوشهر","آبپخش"),
                new CitySeedDto("بوشهر","آبدان"),
                new CitySeedDto("بوشهر","برازجان"),
                new CitySeedDto("بوشهر","بردخون"),
                new CitySeedDto("بوشهر","بردستان"),
                new CitySeedDto("بوشهر","بندردير"),
                new CitySeedDto("بوشهر","بندرديلم"),
                new CitySeedDto("بوشهر","بندرريگ"),
                new CitySeedDto("بوشهر","بندركنگان"),
                new CitySeedDto("بوشهر","بندرگناوه"),
                new CitySeedDto("بوشهر","بنك"),
                new CitySeedDto("بوشهر","بوشهر"),
                new CitySeedDto("بوشهر","تنگ ارم"),
                new CitySeedDto("بوشهر","جم"),
                new CitySeedDto("بوشهر","چغادك"),
                new CitySeedDto("بوشهر","خارك"),
                new CitySeedDto("بوشهر","خورموج"),
                new CitySeedDto("بوشهر","دالكي"),
                new CitySeedDto("بوشهر","دلوار"),
                new CitySeedDto("بوشهر","ريز"),
                new CitySeedDto("بوشهر","سعدآباد"),
                new CitySeedDto("بوشهر","سيراف"),
                new CitySeedDto("بوشهر","شبانكاره"),
                new CitySeedDto("بوشهر","شنبه"),
                new CitySeedDto("بوشهر","عسلويه"),
                new CitySeedDto("بوشهر","كاكي"),
                new CitySeedDto("بوشهر","كلمه"),
                new CitySeedDto("بوشهر","نخل تقي"),
                new CitySeedDto("بوشهر","وحدتيه"),
                new CitySeedDto("تهران","ارجمند"),
                new CitySeedDto("تهران","اسلامشهر"),
                new CitySeedDto("تهران","انديشه"),
                new CitySeedDto("تهران","آبسرد"),
                new CitySeedDto("تهران","آبعلي"),
                new CitySeedDto("تهران","باغستان"),
                new CitySeedDto("تهران","باقرشهر"),
                new CitySeedDto("تهران","بومهن"),
                new CitySeedDto("تهران","پاكدشت"),
                new CitySeedDto("تهران","پرديس"),
                new CitySeedDto("تهران","پيشوا"),
                new CitySeedDto("تهران","تجريش"),
                new CitySeedDto("تهران","تهران"),
                new CitySeedDto("تهران","جوادآباد"),
                new CitySeedDto("تهران","چهاردانگه"),
                new CitySeedDto("تهران","حسن آباد "),
                new CitySeedDto("تهران","دماوند"),
                new CitySeedDto("تهران","رباط كريم"),
                new CitySeedDto("تهران","رودهن"),
                new CitySeedDto("تهران","ري"),
                new CitySeedDto("تهران","شاهدشهر"),
                new CitySeedDto("تهران","شريف آباد"),
                new CitySeedDto("تهران","شهريار"),
                new CitySeedDto("تهران","صالح آباد "),
                new CitySeedDto("تهران","صباشهر"),
                new CitySeedDto("تهران","صفادشت"),
                new CitySeedDto("تهران","فردوسيه"),
                new CitySeedDto("تهران","فرون آباد"),
                new CitySeedDto("تهران","فشم"),
                new CitySeedDto("تهران","فيروزكوه"),
                new CitySeedDto("تهران","قدس"),
                new CitySeedDto("تهران","قرچك"),
                new CitySeedDto("تهران","كهريزك"),
                new CitySeedDto("تهران","كيلان"),
                new CitySeedDto("تهران","گلستان"),
                new CitySeedDto("تهران","لواسان"),
                new CitySeedDto("تهران","ملارد"),
                new CitySeedDto("تهران","نسيم شهر"),
                new CitySeedDto("تهران","نصيرآباد"),
                new CitySeedDto("تهران","وحيديه"),
                new CitySeedDto("تهران","ورامين"),
                new CitySeedDto("چهارمحال وبختياري","اردل"),
                new CitySeedDto("چهارمحال وبختياري","آلوني"),
                new CitySeedDto("چهارمحال وبختياري","باباحيدر"),
                new CitySeedDto("چهارمحال وبختياري","بروجن"),
                new CitySeedDto("چهارمحال وبختياري","بلداجي"),
                new CitySeedDto("چهارمحال وبختياري","بن"),
                new CitySeedDto("چهارمحال وبختياري","جونقان"),
                new CitySeedDto("چهارمحال وبختياري","چلگرد"),
                new CitySeedDto("چهارمحال وبختياري","سامان"),
                new CitySeedDto("چهارمحال وبختياري","سفيددشت"),
                new CitySeedDto("چهارمحال وبختياري","سودجان"),
                new CitySeedDto("چهارمحال وبختياري","سورشجان"),
                new CitySeedDto("چهارمحال وبختياري","شلمزار"),
                new CitySeedDto("چهارمحال وبختياري","شهركرد"),
                new CitySeedDto("چهارمحال وبختياري","طاقانك"),
                new CitySeedDto("چهارمحال وبختياري","فارسان"),
                new CitySeedDto("چهارمحال وبختياري","فرادنبه"),
                new CitySeedDto("چهارمحال وبختياري","فرخ شهر"),
                new CitySeedDto("چهارمحال وبختياري","كيان"),
                new CitySeedDto("چهارمحال وبختياري","گندمان"),
                new CitySeedDto("چهارمحال وبختياري","گهرو"),
                new CitySeedDto("چهارمحال وبختياري","لردگان"),
                new CitySeedDto("چهارمحال وبختياري","مال خليفه"),
                new CitySeedDto("چهارمحال وبختياري","ناغان"),
                new CitySeedDto("چهارمحال وبختياري","نافچ"),
                new CitySeedDto("چهارمحال وبختياري","نقنه"),
                new CitySeedDto("چهارمحال وبختياري","هفشجان"),
                new CitySeedDto("خراسان جنوبي","ارسك"),
                new CitySeedDto("خراسان جنوبي","اسديه"),
                new CitySeedDto("خراسان جنوبي","اسفدن"),
                new CitySeedDto("خراسان جنوبي","اسلاميه"),
                new CitySeedDto("خراسان جنوبي","آرين شهر"),
                new CitySeedDto("خراسان جنوبي","آيسك"),
                new CitySeedDto("خراسان جنوبي","بشرويه"),
                new CitySeedDto("خراسان جنوبي","بيرجند"),
                new CitySeedDto("خراسان جنوبي","حاجي آباد"),
                new CitySeedDto("خراسان جنوبي","خضري دشت بياض"),
                new CitySeedDto("خراسان جنوبي","خوسف"),
                new CitySeedDto("خراسان جنوبي","زهان"),
                new CitySeedDto("خراسان جنوبي","سرايان"),
                new CitySeedDto("خراسان جنوبي","سربيشه"),
                new CitySeedDto("خراسان جنوبي","سه قلعه"),
                new CitySeedDto("خراسان جنوبي","شوسف"),
                new CitySeedDto("خراسان جنوبي","طبس مسينا"),
                new CitySeedDto("خراسان جنوبي","فردوس"),
                new CitySeedDto("خراسان جنوبي","قائن"),
                new CitySeedDto("خراسان جنوبي","قهستان"),
                new CitySeedDto("خراسان جنوبي","گزيك"),
                new CitySeedDto("خراسان جنوبي","محمد شهر"),
                new CitySeedDto("خراسان جنوبي","مود"),
                new CitySeedDto("خراسان جنوبي","نهبندان"),
                new CitySeedDto("خراسان جنوبي","نيمبلوك"),
                new CitySeedDto("خراسان رضوي","احمدآبادصولت"),
                new CitySeedDto("خراسان رضوي","انابد"),
                new CitySeedDto("خراسان رضوي","باجگيران"),
                new CitySeedDto("خراسان رضوي","باخرز"),
                new CitySeedDto("خراسان رضوي","بار"),
                new CitySeedDto("خراسان رضوي","بايگ"),
                new CitySeedDto("خراسان رضوي","بجستان"),
                new CitySeedDto("خراسان رضوي","بردسكن"),
                new CitySeedDto("خراسان رضوي","بيدخت"),
                new CitySeedDto("خراسان رضوي","تايباد"),
                new CitySeedDto("خراسان رضوي","تربت جام"),
                new CitySeedDto("خراسان رضوي","تربت حيدريه"),
                new CitySeedDto("خراسان رضوي","جغتاي"),
                new CitySeedDto("خراسان رضوي","جنگل"),
                new CitySeedDto("خراسان رضوي","چاپشلو"),
                new CitySeedDto("خراسان رضوي","چكنه"),
                new CitySeedDto("خراسان رضوي","چناران"),
                new CitySeedDto("خراسان رضوي","خرو"),
                new CitySeedDto("خراسان رضوي","خليل آباد"),
                new CitySeedDto("خراسان رضوي","خواف"),
                new CitySeedDto("خراسان رضوي","داورزن"),
                new CitySeedDto("خراسان رضوي","درگز"),
                new CitySeedDto("خراسان رضوي","درود"),
                new CitySeedDto("خراسان رضوي","دولت آباد "),
                new CitySeedDto("خراسان رضوي","رباط سنگ"),
                new CitySeedDto("خراسان رضوي","رشتخوار"),
                new CitySeedDto("خراسان رضوي","رضويه"),
                new CitySeedDto("خراسان رضوي","روداب"),
                new CitySeedDto("خراسان رضوي","ريوش"),
                new CitySeedDto("خراسان رضوي","سبزوار"),
                new CitySeedDto("خراسان رضوي","سرخس"),
                new CitySeedDto("خراسان رضوي","سفيدسنگ"),
                new CitySeedDto("خراسان رضوي","سلامي"),
                new CitySeedDto("خراسان رضوي","سلطان آباد"),
                new CitySeedDto("خراسان رضوي","سنگان"),
                new CitySeedDto("خراسان رضوي","شادمهر"),
                new CitySeedDto("خراسان رضوي","شانديز"),
                new CitySeedDto("خراسان رضوي","ششتمد"),
                new CitySeedDto("خراسان رضوي","شهرآباد"),
                new CitySeedDto("خراسان رضوي","شهرزو"),
                new CitySeedDto("خراسان رضوي","صالح آباد  "),
                new CitySeedDto("خراسان رضوي","طرقبه"),
                new CitySeedDto("خراسان رضوي","عشق آباد"),
                new CitySeedDto("خراسان رضوي","فرهادگرد"),
                new CitySeedDto("خراسان رضوي","فريمان"),
                new CitySeedDto("خراسان رضوي","فيروزه"),
                new CitySeedDto("خراسان رضوي","فيض آباد"),
                new CitySeedDto("خراسان رضوي","قاسم آباد"),
                new CitySeedDto("خراسان رضوي","قدمگاه"),
                new CitySeedDto("خراسان رضوي","قلندرآباد"),
                new CitySeedDto("خراسان رضوي","قوچان"),
                new CitySeedDto("خراسان رضوي","كاخك"),
                new CitySeedDto("خراسان رضوي","كاريز"),
                new CitySeedDto("خراسان رضوي","كاشمر"),
                new CitySeedDto("خراسان رضوي","كدكن"),
                new CitySeedDto("خراسان رضوي","كلات"),
                new CitySeedDto("خراسان رضوي","كندر"),
                new CitySeedDto("خراسان رضوي","گلمكان"),
                new CitySeedDto("خراسان رضوي","گناباد"),
                new CitySeedDto("خراسان رضوي","لطف آباد"),
                new CitySeedDto("خراسان رضوي","مزدآوند"),
                new CitySeedDto("خراسان رضوي","مشهد"),
                new CitySeedDto("خراسان رضوي","مشهدريزه"),
                new CitySeedDto("خراسان رضوي","ملك آباد"),
                new CitySeedDto("خراسان رضوي","نشتيفان"),
                new CitySeedDto("خراسان رضوي","نصر آباد"),
                new CitySeedDto("خراسان رضوي","نقاب"),
                new CitySeedDto("خراسان رضوي","نوخندان"),
                new CitySeedDto("خراسان رضوي","نيشابور"),
                new CitySeedDto("خراسان رضوي","نيل شهر"),
                new CitySeedDto("خراسان رضوي","همت آباد"),
                new CitySeedDto("خراسان رضوي","يونسي"),
                new CitySeedDto("خراسان شمالي","اسفراين"),
                new CitySeedDto("خراسان شمالي","ايور"),
                new CitySeedDto("خراسان شمالي","آشخانه"),
                new CitySeedDto("خراسان شمالي","بجنورد"),
                new CitySeedDto("خراسان شمالي","پيش قلعه"),
                new CitySeedDto("خراسان شمالي","تيتكانلو"),
                new CitySeedDto("خراسان شمالي","جاجرم"),
                new CitySeedDto("خراسان شمالي","حصارگرمخان"),
                new CitySeedDto("خراسان شمالي","درق"),
                new CitySeedDto("خراسان شمالي","راز"),
                new CitySeedDto("خراسان شمالي","سنخواست"),
                new CitySeedDto("خراسان شمالي","شوقان"),
                new CitySeedDto("خراسان شمالي","شيروان"),
                new CitySeedDto("خراسان شمالي","صفي آباد"),
                new CitySeedDto("خراسان شمالي","فاروج"),
                new CitySeedDto("خراسان شمالي","قاضي"),
                new CitySeedDto("خراسان شمالي","گرمه"),
                new CitySeedDto("خراسان شمالي","لوجلي"),
                new CitySeedDto("خوزستان","اروندكنار"),
                new CitySeedDto("خوزستان","الوان"),
                new CitySeedDto("خوزستان","اميديه"),
                new CitySeedDto("خوزستان","انديمشك"),
                new CitySeedDto("خوزستان","اهواز"),
                new CitySeedDto("خوزستان","ايذه"),
                new CitySeedDto("خوزستان","آبادان"),
                new CitySeedDto("خوزستان","آغاجاري"),
                new CitySeedDto("خوزستان","باغ ملك"),
                new CitySeedDto("خوزستان","بستان"),
                new CitySeedDto("خوزستان","بندرامام خميني"),
                new CitySeedDto("خوزستان","بندرماهشهر"),
                new CitySeedDto("خوزستان","بهبهان"),
                new CitySeedDto("خوزستان","تركالكي"),
                new CitySeedDto("خوزستان","جايزان"),
                new CitySeedDto("خوزستان","جنت مكان"),
                new CitySeedDto("خوزستان","چغاميش"),
                new CitySeedDto("خوزستان","چمران"),
                new CitySeedDto("خوزستان","چوئبده"),
                new CitySeedDto("خوزستان","حر"),
                new CitySeedDto("خوزستان","حسينيه"),
                new CitySeedDto("خوزستان","حمزه"),
                new CitySeedDto("خوزستان","حميديه"),
                new CitySeedDto("خوزستان","خرمشهر"),
                new CitySeedDto("خوزستان","دارخوين"),
                new CitySeedDto("خوزستان","دزآب"),
                new CitySeedDto("خوزستان","دزفول"),
                new CitySeedDto("خوزستان","دهدز"),
                new CitySeedDto("خوزستان","رامشير"),
                new CitySeedDto("خوزستان","رامهرمز"),
                new CitySeedDto("خوزستان","رفيع"),
                new CitySeedDto("خوزستان","زهره"),
                new CitySeedDto("خوزستان","سالند"),
                new CitySeedDto("خوزستان","سردشت "),
                new CitySeedDto("خوزستان","سماله"),
                new CitySeedDto("خوزستان","سوسنگرد"),
                new CitySeedDto("خوزستان","شادگان"),
                new CitySeedDto("خوزستان","شاوور"),
                new CitySeedDto("خوزستان","شرافت"),
                new CitySeedDto("خوزستان","شوش"),
                new CitySeedDto("خوزستان","شوشتر"),
                new CitySeedDto("خوزستان","شيبان"),
                new CitySeedDto("خوزستان","صالح شهر"),
                new CitySeedDto("خوزستان","صالح مشطط"),
                new CitySeedDto("خوزستان","صفي آباد "),
                new CitySeedDto("خوزستان","صيدون"),
                new CitySeedDto("خوزستان","قلعه تل"),
                new CitySeedDto("خوزستان","قلعه خواجه"),
                new CitySeedDto("خوزستان","گتوند"),
                new CitySeedDto("خوزستان","گوريه"),
                new CitySeedDto("خوزستان","لالي"),
                new CitySeedDto("خوزستان","مسجدسليمان"),
                new CitySeedDto("خوزستان","مشراگه"),
                new CitySeedDto("خوزستان","مقاومت"),
                new CitySeedDto("خوزستان","ملاثاني"),
                new CitySeedDto("خوزستان","ميانرود"),
                new CitySeedDto("خوزستان","ميداود"),
                new CitySeedDto("خوزستان","مينوشهر"),
                new CitySeedDto("خوزستان","ويس"),
                new CitySeedDto("خوزستان","هفتگل"),
                new CitySeedDto("خوزستان","هنديجان"),
                new CitySeedDto("خوزستان","هويزه"),
                new CitySeedDto("زنجان","ابهر"),
                new CitySeedDto("زنجان","ارمغانخانه"),
                new CitySeedDto("زنجان","آب بر"),
                new CitySeedDto("زنجان","چورزق"),
                new CitySeedDto("زنجان","حلب"),
                new CitySeedDto("زنجان","خرمدره"),
                new CitySeedDto("زنجان","دندي"),
                new CitySeedDto("زنجان","زرين آباد"),
                new CitySeedDto("زنجان","زرين رود"),
                new CitySeedDto("زنجان","زنجان"),
                new CitySeedDto("زنجان","سجاس"),
                new CitySeedDto("زنجان","سلطانيه"),
                new CitySeedDto("زنجان","سهرورد"),
                new CitySeedDto("زنجان","صائين قلعه"),
                new CitySeedDto("زنجان","قيدار"),
                new CitySeedDto("زنجان","گرماب"),
                new CitySeedDto("زنجان","ماه نشان"),
                new CitySeedDto("زنجان","هيدج"),
                new CitySeedDto("سمنان","اميريه"),
                new CitySeedDto("سمنان","ايوانكي"),
                new CitySeedDto("سمنان","آرادان"),
                new CitySeedDto("سمنان","بسطام"),
                new CitySeedDto("سمنان","بيارجمند"),
                new CitySeedDto("سمنان","دامغان"),
                new CitySeedDto("سمنان","درجزين"),
                new CitySeedDto("سمنان","ديباج"),
                new CitySeedDto("سمنان","سرخه"),
                new CitySeedDto("سمنان","سمنان"),
                new CitySeedDto("سمنان","شاهرود"),
                new CitySeedDto("سمنان","شهميرزاد"),
                new CitySeedDto("سمنان","كلاته خيج"),
                new CitySeedDto("سمنان","گرمسار"),
                new CitySeedDto("سمنان","مجن"),
                new CitySeedDto("سمنان","مهدي شهر"),
                new CitySeedDto("سمنان","ميامي"),
                new CitySeedDto("سيستان وبلوچستان","اديمي"),
                new CitySeedDto("سيستان وبلوچستان","اسپكه"),
                new CitySeedDto("سيستان وبلوچستان","ايرانشهر"),
                new CitySeedDto("سيستان وبلوچستان","بزمان"),
                new CitySeedDto("سيستان وبلوچستان","بمپور"),
                new CitySeedDto("سيستان وبلوچستان","بنت"),
                new CitySeedDto("سيستان وبلوچستان","بنجار"),
                new CitySeedDto("سيستان وبلوچستان","پيشين"),
                new CitySeedDto("سيستان وبلوچستان","جالق"),
                new CitySeedDto("سيستان وبلوچستان","چاه بهار"),
                new CitySeedDto("سيستان وبلوچستان","خاش"),
                new CitySeedDto("سيستان وبلوچستان","دوست محمد"),
                new CitySeedDto("سيستان وبلوچستان","راسك"),
                new CitySeedDto("سيستان وبلوچستان","زابل"),
                new CitySeedDto("سيستان وبلوچستان","زابلي"),
                new CitySeedDto("سيستان وبلوچستان","زاهدان"),
                new CitySeedDto("سيستان وبلوچستان","زرآباد"),
                new CitySeedDto("سيستان وبلوچستان","زهك"),
                new CitySeedDto("سيستان وبلوچستان","سراوان"),
                new CitySeedDto("سيستان وبلوچستان","سرباز"),
                new CitySeedDto("سيستان وبلوچستان","سوران"),
                new CitySeedDto("سيستان وبلوچستان","سيركان"),
                new CitySeedDto("سيستان وبلوچستان","علي اكبر"),
                new CitySeedDto("سيستان وبلوچستان","فنوج"),
                new CitySeedDto("سيستان وبلوچستان","قصرقند"),
                new CitySeedDto("سيستان وبلوچستان","كنارك"),
                new CitySeedDto("سيستان وبلوچستان","گشت"),
                new CitySeedDto("سيستان وبلوچستان","گلمورتي"),
                new CitySeedDto("سيستان وبلوچستان","محمدان"),
                new CitySeedDto("سيستان وبلوچستان","محمد آباد"),
                new CitySeedDto("سيستان وبلوچستان","محمدي"),
                new CitySeedDto("سيستان وبلوچستان","ميرجاوه"),
                new CitySeedDto("سيستان وبلوچستان","نصرت آباد"),
                new CitySeedDto("سيستان وبلوچستان","نگور"),
                new CitySeedDto("سيستان وبلوچستان","نوك آباد"),
                new CitySeedDto("سيستان وبلوچستان","نيك شهر"),
                new CitySeedDto("سيستان وبلوچستان","هيدوج"),
                new CitySeedDto("فارس","اردكان"),
                new CitySeedDto("فارس","ارسنجان"),
                new CitySeedDto("فارس","استهبان"),
                new CitySeedDto("فارس","اسير"),
                new CitySeedDto("فارس","اشكنان"),
                new CitySeedDto("فارس","افزر"),
                new CitySeedDto("فارس","اقليد"),
                new CitySeedDto("فارس","امام شهر"),
                new CitySeedDto("فارس","اوز"),
                new CitySeedDto("فارس","اهل"),
                new CitySeedDto("فارس","ايج"),
                new CitySeedDto("فارس","ايزدخواست"),
                new CitySeedDto("فارس","آباده"),
                new CitySeedDto("فارس","آباده طشك"),
                new CitySeedDto("فارس","باب انار"),
                new CitySeedDto("فارس","بالاده"),
                new CitySeedDto("فارس","بنارويه"),
                new CitySeedDto("فارس","بوانات"),
                new CitySeedDto("فارس","بهمن"),
                new CitySeedDto("فارس","بيرم"),
                new CitySeedDto("فارس","بيضا"),
                new CitySeedDto("فارس","جنت شهر"),
                new CitySeedDto("فارس","جويم"),
                new CitySeedDto("فارس","جهرم"),
                new CitySeedDto("فارس","حاجي آباد "),
                new CitySeedDto("فارس","حسامي"),
                new CitySeedDto("فارس","حسن آباد  "),
                new CitySeedDto("فارس","خانه زنيان"),
                new CitySeedDto("فارس","خاوران"),
                new CitySeedDto("فارس","خرامه"),
                new CitySeedDto("فارس","خشت"),
                new CitySeedDto("فارس","خنج"),
                new CitySeedDto("فارس","خور "),
                new CitySeedDto("فارس","خومه زار"),
                new CitySeedDto("فارس","داراب"),
                new CitySeedDto("فارس","داريان"),
                new CitySeedDto("فارس","دبيران"),
                new CitySeedDto("فارس","دژكرد"),
                new CitySeedDto("فارس","دوبرجي"),
                new CitySeedDto("فارس","دوزه"),
                new CitySeedDto("فارس","دهرم"),
                new CitySeedDto("فارس","رامجرد"),
                new CitySeedDto("فارس","رونيز"),
                new CitySeedDto("فارس","زاهدشهر"),
                new CitySeedDto("فارس","زرقان"),
                new CitySeedDto("فارس","سده"),
                new CitySeedDto("فارس","سروستان"),
                new CitySeedDto("فارس","سعادت شهر"),
                new CitySeedDto("فارس","سورمق"),
                new CitySeedDto("فارس","سيدان"),
                new CitySeedDto("فارس","ششده"),
                new CitySeedDto("فارس","شهر جديد صدرا"),
                new CitySeedDto("فارس","شهرپير"),
                new CitySeedDto("فارس","شيراز"),
                new CitySeedDto("فارس","صغاد"),
                new CitySeedDto("فارس","صفاشهر"),
                new CitySeedDto("فارس","علامرودشت"),
                new CitySeedDto("فارس","عمادده"),
                new CitySeedDto("فارس","فدامي"),
                new CitySeedDto("فارس","فراشبند"),
                new CitySeedDto("فارس","فسا"),
                new CitySeedDto("فارس","فيروزآباد"),
                new CitySeedDto("فارس","قادرآباد"),
                new CitySeedDto("فارس","قائميه"),
                new CitySeedDto("فارس","قطب آباد"),
                new CitySeedDto("فارس","قطرويه"),
                new CitySeedDto("فارس","قير"),
                new CitySeedDto("فارس","كارزين"),
                new CitySeedDto("فارس","كازرون"),
                new CitySeedDto("فارس","كامفيروز"),
                new CitySeedDto("فارس","كره اي"),
                new CitySeedDto("فارس","كنارتخته"),
                new CitySeedDto("فارس","كوار"),
                new CitySeedDto("فارس","كوهنجان"),
                new CitySeedDto("فارس","گراش"),
                new CitySeedDto("فارس","گله دار"),
                new CitySeedDto("فارس","لار"),
                new CitySeedDto("فارس","لامرد"),
                new CitySeedDto("فارس","لپوئي"),
                new CitySeedDto("فارس","لطيفي"),
                new CitySeedDto("فارس","مبارك آباد"),
                new CitySeedDto("فارس","مرودشت"),
                new CitySeedDto("فارس","مشكان"),
                new CitySeedDto("فارس","مصيري"),
                new CitySeedDto("فارس","مهر"),
                new CitySeedDto("فارس","ميمند"),
                new CitySeedDto("فارس","نوبندگان"),
                new CitySeedDto("فارس","نوجين"),
                new CitySeedDto("فارس","نودان"),
                new CitySeedDto("فارس","نورآباد"),
                new CitySeedDto("فارس","ني ريز"),
                new CitySeedDto("فارس","وراوي"),
                new CitySeedDto("فارس","هماشهر"),
                new CitySeedDto("قزوين","ارداق"),
                new CitySeedDto("قزوين","اسفرورين"),
                new CitySeedDto("قزوين","اقباليه"),
                new CitySeedDto("قزوين","الوند"),
                new CitySeedDto("قزوين","آبگرم"),
                new CitySeedDto("قزوين","آبيك"),
                new CitySeedDto("قزوين","آوج"),
                new CitySeedDto("قزوين","بوئين زهرا"),
                new CitySeedDto("قزوين","بيدستان"),
                new CitySeedDto("قزوين","تاكستان"),
                new CitySeedDto("قزوين","خاكعلي"),
                new CitySeedDto("قزوين","خرمدشت"),
                new CitySeedDto("قزوين","دانسفهان"),
                new CitySeedDto("قزوين","رازميان"),
                new CitySeedDto("قزوين","سگزآباد"),
                new CitySeedDto("قزوين","سيردان"),
                new CitySeedDto("قزوين","شال"),
                new CitySeedDto("قزوين","شريفيه"),
                new CitySeedDto("قزوين","ضياءآباد"),
                new CitySeedDto("قزوين","قزوين"),
                new CitySeedDto("قزوين","كوهين"),
                new CitySeedDto("قزوين","محمديه"),
                new CitySeedDto("قزوين","محمودآبادنمونه"),
                new CitySeedDto("قزوين","معلم كلايه"),
                new CitySeedDto("قزوين","نرجه"),
                new CitySeedDto("قم","جعفريه"),
                new CitySeedDto("قم","دستجرد"),
                new CitySeedDto("قم","سلفچگان"),
                new CitySeedDto("قم","قم"),
                new CitySeedDto("قم","قنوات"),
                new CitySeedDto("قم","كهك"),
                new CitySeedDto("كردستان","آرمرده"),
                new CitySeedDto("كردستان","بابارشاني"),
                new CitySeedDto("كردستان","بانه"),
                new CitySeedDto("كردستان","بلبان آباد"),
                new CitySeedDto("كردستان","بوئين سفلي"),
                new CitySeedDto("كردستان","بيجار"),
                new CitySeedDto("كردستان","چناره"),
                new CitySeedDto("كردستان","دزج"),
                new CitySeedDto("كردستان","دلبران"),
                new CitySeedDto("كردستان","دهگلان"),
                new CitySeedDto("كردستان","ديواندره"),
                new CitySeedDto("كردستان","زرينه"),
                new CitySeedDto("كردستان","سروآباد"),
                new CitySeedDto("كردستان","سريش آباد"),
                new CitySeedDto("كردستان","سقز"),
                new CitySeedDto("كردستان","سنندج"),
                new CitySeedDto("كردستان","شويشه"),
                new CitySeedDto("كردستان","صاحب"),
                new CitySeedDto("كردستان","قروه"),
                new CitySeedDto("كردستان","كامياران"),
                new CitySeedDto("كردستان","كاني دينار"),
                new CitySeedDto("كردستان","كاني سور"),
                new CitySeedDto("كردستان","مريوان"),
                new CitySeedDto("كردستان","موچش"),
                new CitySeedDto("كردستان","ياسوكند"),
                new CitySeedDto("كرمان","اختيارآباد"),
                new CitySeedDto("كرمان","ارزوئيه"),
                new CitySeedDto("كرمان","امين شهر"),
                new CitySeedDto("كرمان","انار"),
                new CitySeedDto("كرمان","اندوهجرد"),
                new CitySeedDto("كرمان","باغين"),
                new CitySeedDto("كرمان","بافت"),
                new CitySeedDto("كرمان","بردسير"),
                new CitySeedDto("كرمان","بروات"),
                new CitySeedDto("كرمان","بزنجان"),
                new CitySeedDto("كرمان","بم"),
                new CitySeedDto("كرمان","بهرمان"),
                new CitySeedDto("كرمان","پاريز"),
                new CitySeedDto("كرمان","جبالبارز"),
                new CitySeedDto("كرمان","جوپار"),
                new CitySeedDto("كرمان","جوزم"),
                new CitySeedDto("كرمان","جيرفت"),
                new CitySeedDto("كرمان","چترود"),
                new CitySeedDto("كرمان","خاتون آباد"),
                new CitySeedDto("كرمان","خانوك"),
                new CitySeedDto("كرمان","خورسند"),
                new CitySeedDto("كرمان","درب بهشت"),
                new CitySeedDto("كرمان","دوساري"),
                new CitySeedDto("كرمان","دهج"),
                new CitySeedDto("كرمان","رابر"),
                new CitySeedDto("كرمان","راور"),
                new CitySeedDto("كرمان","راين"),
                new CitySeedDto("كرمان","رفسنجان"),
                new CitySeedDto("كرمان","رودبار"),
                new CitySeedDto("كرمان","ريحان شهر"),
                new CitySeedDto("كرمان","زرند"),
                new CitySeedDto("كرمان","زنگي آباد"),
                new CitySeedDto("كرمان","زيدآباد"),
                new CitySeedDto("كرمان","سرچشمه"),
                new CitySeedDto("كرمان","سيرجان"),
                new CitySeedDto("كرمان","شهداد"),
                new CitySeedDto("كرمان","شهربابك"),
                new CitySeedDto("كرمان","صفائيه"),
                new CitySeedDto("كرمان","عنبرآباد"),
                new CitySeedDto("كرمان","فارياب"),
                new CitySeedDto("كرمان","فهرج"),
                new CitySeedDto("كرمان","قلعه گنج"),
                new CitySeedDto("كرمان","كاظم آباد"),
                new CitySeedDto("كرمان","كرمان"),
                new CitySeedDto("كرمان","كشكوئيه"),
                new CitySeedDto("كرمان","كوهبنان"),
                new CitySeedDto("كرمان","كهنوج"),
                new CitySeedDto("كرمان","كيانشهر"),
                new CitySeedDto("كرمان","گلباف"),
                new CitySeedDto("كرمان","گلزار"),
                new CitySeedDto("كرمان","لاله زار"),
                new CitySeedDto("كرمان","ماهان"),
                new CitySeedDto("كرمان","محمد آباد "),
                new CitySeedDto("كرمان","محي آباد"),
                new CitySeedDto("كرمان","مردهك"),
                new CitySeedDto("كرمان","منوجان"),
                new CitySeedDto("كرمان","نجف شهر"),
                new CitySeedDto("كرمان","نرماشير"),
                new CitySeedDto("كرمان","نظام شهر"),
                new CitySeedDto("كرمان","نگار"),
                new CitySeedDto("كرمان","نودژ"),
                new CitySeedDto("كرمان","هجدك"),
                new CitySeedDto("كرمان","هماشهر "),
                new CitySeedDto("كرمان","يزدان شهر"),
                new CitySeedDto("كرمانشاه","ازگله"),
                new CitySeedDto("كرمانشاه","اسلام آبادغرب"),
                new CitySeedDto("كرمانشاه","باينگان"),
                new CitySeedDto("كرمانشاه","بيستون"),
                new CitySeedDto("كرمانشاه","پاوه"),
                new CitySeedDto("كرمانشاه","تازه آباد"),
                new CitySeedDto("كرمانشاه","جوانرود"),
                new CitySeedDto("كرمانشاه","حميل"),
                new CitySeedDto("كرمانشاه","رباط"),
                new CitySeedDto("كرمانشاه","روانسر"),
                new CitySeedDto("كرمانشاه","سرپل ذهاب"),
                new CitySeedDto("كرمانشاه","سرمست"),
                new CitySeedDto("كرمانشاه","سطر"),
                new CitySeedDto("كرمانشاه","سنقر"),
                new CitySeedDto("كرمانشاه","سومار"),
                new CitySeedDto("كرمانشاه","شاهو"),
                new CitySeedDto("كرمانشاه","صحنه"),
                new CitySeedDto("كرمانشاه","قصرشيرين"),
                new CitySeedDto("كرمانشاه","كرمانشاه"),
                new CitySeedDto("كرمانشاه","كرندغرب"),
                new CitySeedDto("كرمانشاه","كنگاور"),
                new CitySeedDto("كرمانشاه","كوزران"),
                new CitySeedDto("كرمانشاه","گهواره"),
                new CitySeedDto("كرمانشاه","گيلانغرب"),
                new CitySeedDto("كرمانشاه","ميان راهان"),
                new CitySeedDto("كرمانشاه","نودشه"),
                new CitySeedDto("كرمانشاه","نوسود"),
                new CitySeedDto("كرمانشاه","هرسين"),
                new CitySeedDto("كرمانشاه","هلشي"),
                new CitySeedDto("كهگيلويه وبويراحمد","باشت"),
                new CitySeedDto("كهگيلويه وبويراحمد","پاتاوه"),
                new CitySeedDto("كهگيلويه وبويراحمد","چرام"),
                new CitySeedDto("كهگيلويه وبويراحمد","چيتاب"),
                new CitySeedDto("كهگيلويه وبويراحمد","دوگنبدان"),
                new CitySeedDto("كهگيلويه وبويراحمد","دهدشت"),
                new CitySeedDto("كهگيلويه وبويراحمد","ديشموك"),
                new CitySeedDto("كهگيلويه وبويراحمد","سوق"),
                new CitySeedDto("كهگيلويه وبويراحمد","سي سخت"),
                new CitySeedDto("كهگيلويه وبويراحمد","قلعه رئيسي"),
                new CitySeedDto("كهگيلويه وبويراحمد","گراب سفلي"),
                new CitySeedDto("كهگيلويه وبويراحمد","لنده"),
                new CitySeedDto("كهگيلويه وبويراحمد","ليكك"),
                new CitySeedDto("كهگيلويه وبويراحمد","مادوان"),
                new CitySeedDto("كهگيلويه وبويراحمد","مارگون"),
                new CitySeedDto("كهگيلويه وبويراحمد","ياسوج"),
                new CitySeedDto("گلستان","انبارآلوم"),
                new CitySeedDto("گلستان","اينچه برون"),
                new CitySeedDto("گلستان","آزادشهر"),
                new CitySeedDto("گلستان","آق قلا"),
                new CitySeedDto("گلستان","بندرگز"),
                new CitySeedDto("گلستان","تركمن"),
                new CitySeedDto("گلستان","جلين"),
                new CitySeedDto("گلستان","خان ببين"),
                new CitySeedDto("گلستان","دلند"),
                new CitySeedDto("گلستان","راميان"),
                new CitySeedDto("گلستان","سرخنكلاته"),
                new CitySeedDto("گلستان","سيمين شهر"),
                new CitySeedDto("گلستان","علي آباد"),
                new CitySeedDto("گلستان","فاضل آباد"),
                new CitySeedDto("گلستان","كردكوي"),
                new CitySeedDto("گلستان","كلاله"),
                new CitySeedDto("گلستان","گاليكش"),
                new CitySeedDto("گلستان","گرگان"),
                new CitySeedDto("گلستان","گميش تپه"),
                new CitySeedDto("گلستان","گنبد كاووس"),
                new CitySeedDto("گلستان","مراوه تپه"),
                new CitySeedDto("گلستان","مينودشت"),
                new CitySeedDto("گلستان","نگين شهر"),
                new CitySeedDto("گلستان","نوده خاندوز"),
                new CitySeedDto("گلستان","نوكنده"),
                new CitySeedDto("گيلان","احمدسرگوراب"),
                new CitySeedDto("گيلان","اسالم"),
                new CitySeedDto("گيلان","اطاقور"),
                new CitySeedDto("گيلان","املش"),
                new CitySeedDto("گيلان","آستارا"),
                new CitySeedDto("گيلان","آستانه اشرفيه"),
                new CitySeedDto("گيلان","بازارجمعه"),
                new CitySeedDto("گيلان","بره سر"),
                new CitySeedDto("گيلان","بندرانزلي"),
                new CitySeedDto("گيلان","پره سر"),
                new CitySeedDto("گيلان","توتكابن"),
                new CitySeedDto("گيلان","جيرنده"),
                new CitySeedDto("گيلان","چابكسر"),
                new CitySeedDto("گيلان","چاف وچمخاله"),
                new CitySeedDto("گيلان","چوبر"),
                new CitySeedDto("گيلان","حويق"),
                new CitySeedDto("گيلان","خشكبيجار"),
                new CitySeedDto("گيلان","خمام"),
                new CitySeedDto("گيلان","ديلمان"),
                new CitySeedDto("گيلان","رانكوه"),
                new CitySeedDto("گيلان","رحيم آباد"),
                new CitySeedDto("گيلان","رستم آباد"),
                new CitySeedDto("گيلان","رشت"),
                new CitySeedDto("گيلان","رضوانشهر "),
                new CitySeedDto("گيلان","رودبار "),
                new CitySeedDto("گيلان","رودبنه"),
                new CitySeedDto("گيلان","رودسر"),
                new CitySeedDto("گيلان","سنگر"),
                new CitySeedDto("گيلان","سياهكل"),
                new CitySeedDto("گيلان","شفت"),
                new CitySeedDto("گيلان","شلمان"),
                new CitySeedDto("گيلان","صومعه سرا"),
                new CitySeedDto("گيلان","فومن"),
                new CitySeedDto("گيلان","كلاچاي"),
                new CitySeedDto("گيلان","كوچصفهان"),
                new CitySeedDto("گيلان","كومله"),
                new CitySeedDto("گيلان","كياشهر"),
                new CitySeedDto("گيلان","گوراب زرميخ"),
                new CitySeedDto("گيلان","لاهيجان"),
                new CitySeedDto("گيلان","لشت نشاء"),
                new CitySeedDto("گيلان","لنگرود"),
                new CitySeedDto("گيلان","لوشان"),
                new CitySeedDto("گيلان","لولمان"),
                new CitySeedDto("گيلان","لوندويل"),
                new CitySeedDto("گيلان","ليسار"),
                new CitySeedDto("گيلان","ماسال"),
                new CitySeedDto("گيلان","ماسوله"),
                new CitySeedDto("گيلان","مرجقل"),
                new CitySeedDto("گيلان","منجيل"),
                new CitySeedDto("گيلان","واجارگاه"),
                new CitySeedDto("گيلان","هشتپر"),
                new CitySeedDto("لرستان","ازنا"),
                new CitySeedDto("لرستان","اشترينان"),
                new CitySeedDto("لرستان","الشتر"),
                new CitySeedDto("لرستان","اليگودرز"),
                new CitySeedDto("لرستان","بروجرد"),
                new CitySeedDto("لرستان","پلدختر"),
                new CitySeedDto("لرستان","چالانچولان"),
                new CitySeedDto("لرستان","چغلوندي"),
                new CitySeedDto("لرستان","چقابل"),
                new CitySeedDto("لرستان","خرم آباد"),
                new CitySeedDto("لرستان","درب گنبد"),
                new CitySeedDto("لرستان","دورود"),
                new CitySeedDto("لرستان","زاغه"),
                new CitySeedDto("لرستان","سپيددشت"),
                new CitySeedDto("لرستان","سراب دوره"),
                new CitySeedDto("لرستان","شول آباد"),
                new CitySeedDto("لرستان","فيروز آباد"),
                new CitySeedDto("لرستان","كوناني"),
                new CitySeedDto("لرستان","كوهدشت"),
                new CitySeedDto("لرستان","گراب"),
                new CitySeedDto("لرستان","معمولان"),
                new CitySeedDto("لرستان","مؤمن آباد"),
                new CitySeedDto("لرستان","نور آباد"),
                new CitySeedDto("لرستان","ويسيان"),
                new CitySeedDto("لرستان","هفت چشمه"),
                new CitySeedDto("مازندران","اميركلا"),
                new CitySeedDto("مازندران","ايزدشهر"),
                new CitySeedDto("مازندران","آلاشت"),
                new CitySeedDto("مازندران","آمل"),
                new CitySeedDto("مازندران","بابل"),
                new CitySeedDto("مازندران","بابلسر"),
                new CitySeedDto("مازندران","بلده"),
                new CitySeedDto("مازندران","بهشهر"),
                new CitySeedDto("مازندران","بهنمير"),
                new CitySeedDto("مازندران","پل سفيد"),
                new CitySeedDto("مازندران","پول"),
                new CitySeedDto("مازندران","تنكابن"),
                new CitySeedDto("مازندران","جويبار"),
                new CitySeedDto("مازندران","چالوس"),
                new CitySeedDto("مازندران","چمستان"),
                new CitySeedDto("مازندران","خرم آباد "),
                new CitySeedDto("مازندران","خليل شهر"),
                new CitySeedDto("مازندران","خوش رودپي"),
                new CitySeedDto("مازندران","دابودشت"),
                new CitySeedDto("مازندران","رامسر"),
                new CitySeedDto("مازندران","رستمكلا"),
                new CitySeedDto("مازندران","رويان"),
                new CitySeedDto("مازندران","رينه"),
                new CitySeedDto("مازندران","زرگر محله"),
                new CitySeedDto("مازندران","زيرآب"),
                new CitySeedDto("مازندران","ساري"),
                new CitySeedDto("مازندران","سرخرود"),
                new CitySeedDto("مازندران","سلمان شهر"),
                new CitySeedDto("مازندران","سورك"),
                new CitySeedDto("مازندران","شيرگاه"),
                new CitySeedDto("مازندران","شيرود"),
                new CitySeedDto("مازندران","عباس آباد"),
                new CitySeedDto("مازندران","فريدونكنار"),
                new CitySeedDto("مازندران","فريم"),
                new CitySeedDto("مازندران","قائم شهر"),
                new CitySeedDto("مازندران","كتالم وسادات شهر"),
                new CitySeedDto("مازندران","كلارآباد"),
                new CitySeedDto("مازندران","كلاردشت"),
                new CitySeedDto("مازندران","كله بست"),
                new CitySeedDto("مازندران","كوهي خيل"),
                new CitySeedDto("مازندران","كياسر"),
                new CitySeedDto("مازندران","كياكلا"),
                new CitySeedDto("مازندران","گتاب"),
                new CitySeedDto("مازندران","گزنك"),
                new CitySeedDto("مازندران","گلوگاه"),
                new CitySeedDto("مازندران","محمود آباد"),
                new CitySeedDto("مازندران","مرزن آباد"),
                new CitySeedDto("مازندران","مرزيكلا"),
                new CitySeedDto("مازندران","نشتارود"),
                new CitySeedDto("مازندران","نكا"),
                new CitySeedDto("مازندران","نور"),
                new CitySeedDto("مازندران","نوشهر"),
                new CitySeedDto("مركزي","اراك"),
                new CitySeedDto("مركزي","آستانه"),
                new CitySeedDto("مركزي","آشتيان"),
                new CitySeedDto("مركزي","پرندك"),
                new CitySeedDto("مركزي","تفرش"),
                new CitySeedDto("مركزي","توره"),
                new CitySeedDto("مركزي","جاورسيان"),
                new CitySeedDto("مركزي","خشكرود"),
                new CitySeedDto("مركزي","خمين"),
                new CitySeedDto("مركزي","خنداب"),
                new CitySeedDto("مركزي","داودآباد"),
                new CitySeedDto("مركزي","دليجان"),
                new CitySeedDto("مركزي","رازقان"),
                new CitySeedDto("مركزي","زاويه"),
                new CitySeedDto("مركزي","ساروق"),
                new CitySeedDto("مركزي","ساوه"),
                new CitySeedDto("مركزي","سنجان"),
                new CitySeedDto("مركزي","شازند"),
                new CitySeedDto("مركزي","شهرجديدمهاجران"),
                new CitySeedDto("مركزي","غرق آباد"),
                new CitySeedDto("مركزي","فرمهين"),
                new CitySeedDto("مركزي","قورچي باشي"),
                new CitySeedDto("مركزي","كرهرود"),
                new CitySeedDto("مركزي","كميجان"),
                new CitySeedDto("مركزي","مأمونيه"),
                new CitySeedDto("مركزي","محلات"),
                new CitySeedDto("مركزي","ميلاجرد"),
                new CitySeedDto("مركزي","نراق"),
                new CitySeedDto("مركزي","نوبران"),
                new CitySeedDto("مركزي","نيمور"),
                new CitySeedDto("مركزي","هندودر"),
                new CitySeedDto("هرمزگان","ابوموسي"),
                new CitySeedDto("هرمزگان","بستك"),
                new CitySeedDto("هرمزگان","بندرجاسك"),
                new CitySeedDto("هرمزگان","بندرچارك"),
                new CitySeedDto("هرمزگان","بندرعباس"),
                new CitySeedDto("هرمزگان","بندرلنگه"),
                new CitySeedDto("هرمزگان","بيكاه"),
                new CitySeedDto("هرمزگان","پارسيان"),
                new CitySeedDto("هرمزگان","تخت"),
                new CitySeedDto("هرمزگان","جناح"),
                new CitySeedDto("هرمزگان","حاجي آباد  "),
                new CitySeedDto("هرمزگان","خمير"),
                new CitySeedDto("هرمزگان","درگهان"),
                new CitySeedDto("هرمزگان","دهبارز"),
                new CitySeedDto("هرمزگان","رويدر"),
                new CitySeedDto("هرمزگان","زيارتعلي"),
                new CitySeedDto("هرمزگان","سردشت بشاگرد"),
                new CitySeedDto("هرمزگان","سرگز"),
                new CitySeedDto("هرمزگان","سندرك"),
                new CitySeedDto("هرمزگان","سوزا"),
                new CitySeedDto("هرمزگان","سيريك"),
                new CitySeedDto("هرمزگان","فارغان"),
                new CitySeedDto("هرمزگان","فين"),
                new CitySeedDto("هرمزگان","قشم"),
                new CitySeedDto("هرمزگان","قلعه قاضي"),
                new CitySeedDto("هرمزگان","كنگ"),
                new CitySeedDto("هرمزگان","كوشكنار"),
                new CitySeedDto("هرمزگان","كيش"),
                new CitySeedDto("هرمزگان","گوهران"),
                new CitySeedDto("هرمزگان","ميناب"),
                new CitySeedDto("هرمزگان","هرمز"),
                new CitySeedDto("هرمزگان","هشتبندي"),
                new CitySeedDto("همدان","ازندريان"),
                new CitySeedDto("همدان","اسدآباد"),
                new CitySeedDto("همدان","برزول"),
                new CitySeedDto("همدان","بهار"),
                new CitySeedDto("همدان","تويسركان"),
                new CitySeedDto("همدان","جورقان"),
                new CitySeedDto("همدان","جوكار"),
                new CitySeedDto("همدان","دمق"),
                new CitySeedDto("همدان","رزن"),
                new CitySeedDto("همدان","زنگنه"),
                new CitySeedDto("همدان","سامن"),
                new CitySeedDto("همدان","سركان"),
                new CitySeedDto("همدان","شيرين سو"),
                new CitySeedDto("همدان","صالح آباد   "),
                new CitySeedDto("همدان","فامنين"),
                new CitySeedDto("همدان","فرسفج"),
                new CitySeedDto("همدان","فيروزان"),
                new CitySeedDto("همدان","قروه در جزين"),
                new CitySeedDto("همدان","قهاوند"),
                new CitySeedDto("همدان","كبودرآهنگ"),
                new CitySeedDto("همدان","گل تپه"),
                new CitySeedDto("همدان","گيان"),
                new CitySeedDto("همدان","لالجين"),
                new CitySeedDto("همدان","مريانج"),
                new CitySeedDto("همدان","ملاير"),
                new CitySeedDto("همدان","نهاوند"),
                new CitySeedDto("همدان","همدان"),
                new CitySeedDto("يزد","ابركوه"),
                new CitySeedDto("يزد","احمدآباد"),
                new CitySeedDto("يزد","اردكان "),
                new CitySeedDto("يزد","اشكذر"),
                new CitySeedDto("يزد","بافق"),
                new CitySeedDto("يزد","بفروئيه"),
                new CitySeedDto("يزد","بهاباد"),
                new CitySeedDto("يزد","تفت"),
                new CitySeedDto("يزد","حميديا"),
                new CitySeedDto("يزد","خضرآباد"),
                new CitySeedDto("يزد","ديهوك"),
                new CitySeedDto("يزد","زارچ"),
                new CitySeedDto("يزد","شاهديه"),
                new CitySeedDto("يزد","طبس"),
                new CitySeedDto("يزد","عشق آباد "),
                new CitySeedDto("يزد","عقدا"),
                new CitySeedDto("يزد","مروست"),
                new CitySeedDto("يزد","مهردشت"),
                new CitySeedDto("يزد","مهريز"),
                new CitySeedDto("يزد","ميبد"),
                new CitySeedDto("يزد","ندوشن"),
                new CitySeedDto("يزد","نير "),
                new CitySeedDto("يزد","هرات"),
                new CitySeedDto("يزد","يزد"),
            };
            return list;
        }

        private class CitySeedDto
        {
            public CitySeedDto(string pname, string cname)
            {
                CityName = cname;
                ParentCityName = pname;
            }
            public string ParentCityName { get; set; }
            public string CityName { get; set; }
        }
        #endregion    
    }
}
