// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MajlesMefa.Back.Entities;

#nullable disable

namespace MajlesMefa.Back.Migrations
{
    [DbContext(typeof(RefahMajlesDbContext))]
    [Migration("20230426130803_PageRoles")]
    partial class PageRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MajlesMefa.Back.Entities.ActionReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("ActRefType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVisibleForSenator")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SeenDateBySenator")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SeenDateByToUser")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("DataEntryId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("ActionReferences");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.BussinessRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("RoleType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("BussinessRoles");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("DataEntryType")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("nvarchar(124)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Order");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ParentCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("ParentCityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DataEntryType")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("SenatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Created");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SenatorId");

                    b.ToTable("DataEntries");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.MokatebeEntity", b =>
                {
                    b.Property<Guid>("DataEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GardeshErjaat")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MokatebeKonande")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte>("MokatebeType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ShomareDabirkhane")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ShomareDabirkhaneMarkazi")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("TarikhDabirKhane")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhDabirKhaneMarkazi")
                        .HasColumnType("datetime2");

                    b.HasKey("DataEntryId");

                    b.ToTable("Mokatebes");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.NotghEntity", b =>
                {
                    b.Property<Guid>("DataEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DataEntryId");

                    b.ToTable("Notghs");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.PeygiriEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("PeygiriDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeygiriKonande")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("DataEntryId");

                    b.ToTable("Peygiries");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.TazakorKatbiEntity", b =>
                {
                    b.Property<Guid>("DataEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DataEntryId");

                    b.ToTable("TazakorKatbis");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.TazakorShafahiEntity", b =>
                {
                    b.Property<Guid>("DataEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DataEntryId");

                    b.ToTable("TazakorShafahis");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("ParentId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.PageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.PageRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PgaeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("RoleId");

                    b.ToTable("PageRoles");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.SenatorProfileEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BirthCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComissionMembership")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("HozeCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobHistory")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PersonalFavorites")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PoliticalTending")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("SenaHistory")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("SocailActivity")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("UserId");

                    b.HasIndex("BirthCityId");

                    b.HasIndex("CityId");

                    b.HasIndex("HozeCityId");

                    b.ToTable("SenatorProfiles");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Created");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.ActionReferenceEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.DataEntryEntity", "DataEntry")
                        .WithMany("ActionReferences")
                        .HasForeignKey("DataEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajlesMefa.Back.Entities.UserEntity", "FromUser")
                        .WithMany("FromActionReferences")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajlesMefa.Back.Entities.UserEntity", "ToUser")
                        .WithMany("ToActionReferences")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataEntry");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.CategoryEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.CategoryEntity", "Parent")
                        .WithMany("Categories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.CityEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.CityEntity", "Parent")
                        .WithMany("SubCities")
                        .HasForeignKey("ParentCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.CategoryEntity", "Category")
                        .WithMany("DataEntries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MajlesMefa.Back.Entities.UserEntity", "Creator")
                        .WithMany("CreatorDataEntries")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajlesMefa.Back.Entities.UserEntity", "Senator")
                        .WithMany("SenatorsDataEntries")
                        .HasForeignKey("SenatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Senator");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.MokatebeEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.DataEntryEntity", "DataEntry")
                        .WithOne("Mokatebe")
                        .HasForeignKey("MajlesMefa.Back.Entities.DataEntryTypesEntities.MokatebeEntity", "DataEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataEntry");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.NotghEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.DataEntryEntity", "DataEntry")
                        .WithOne("Notgh")
                        .HasForeignKey("MajlesMefa.Back.Entities.DataEntryTypesEntities.NotghEntity", "DataEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataEntry");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.PeygiriEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.DataEntryEntity", "DataEntry")
                        .WithMany("PeygiriEntities")
                        .HasForeignKey("DataEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataEntry");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.TazakorKatbiEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.DataEntryEntity", "DataEntry")
                        .WithOne("TazakorKatbi")
                        .HasForeignKey("MajlesMefa.Back.Entities.DataEntryTypesEntities.TazakorKatbiEntity", "DataEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataEntry");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryTypesEntities.TazakorShafahiEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.DataEntryEntity", "DataEntry")
                        .WithOne("TazakorShafahi")
                        .HasForeignKey("MajlesMefa.Back.Entities.DataEntryTypesEntities.TazakorShafahiEntity", "DataEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataEntry");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.OrganizationEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.OrganizationEntity", "Parent")
                        .WithMany("SubOrganizations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.PageRoleEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.PageEntity", "Page")
                        .WithMany()
                        .HasForeignKey("PageId");

                    b.HasOne("MajlesMefa.Back.Entities.BussinessRoleEntity", "Role")
                        .WithMany("PageRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.SenatorProfileEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.CityEntity", "BirthCity")
                        .WithMany("SenatorBirthCities")
                        .HasForeignKey("BirthCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajlesMefa.Back.Entities.CityEntity", "City")
                        .WithMany("SenatorCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajlesMefa.Back.Entities.CityEntity", "HozeCity")
                        .WithMany("SenatorHozeCities")
                        .HasForeignKey("HozeCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajlesMefa.Back.Entities.UserEntity", "User")
                        .WithOne("SenatorProfile")
                        .HasForeignKey("MajlesMefa.Back.Entities.SenatorProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthCity");

                    b.Navigation("City");

                    b.Navigation("HozeCity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.UserEntity", b =>
                {
                    b.HasOne("MajlesMefa.Back.Entities.CityEntity", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MajlesMefa.Back.Entities.OrganizationEntity", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("City");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.BussinessRoleEntity", b =>
                {
                    b.Navigation("PageRoles");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("DataEntries");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.CityEntity", b =>
                {
                    b.Navigation("SenatorBirthCities");

                    b.Navigation("SenatorCities");

                    b.Navigation("SenatorHozeCities");

                    b.Navigation("SubCities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.DataEntryEntity", b =>
                {
                    b.Navigation("ActionReferences");

                    b.Navigation("Mokatebe");

                    b.Navigation("Notgh");

                    b.Navigation("PeygiriEntities");

                    b.Navigation("TazakorKatbi");

                    b.Navigation("TazakorShafahi");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("SubOrganizations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MajlesMefa.Back.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatorDataEntries");

                    b.Navigation("FromActionReferences");

                    b.Navigation("SenatorProfile");

                    b.Navigation("SenatorsDataEntries");

                    b.Navigation("ToActionReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
